on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        shell: pwsh
        run: |
          ./Tools/setup.ps1
          Invoke-Build -Task ShowInfo
      - name: Build
        shell: pwsh
        run: |
          Invoke-Build -Task Clean, Build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Release
          path: ./Release/

  test_on_windows:
    name: Test Module on Windows (PS v5)
    runs-on: windows-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: Release
          path: ./Release/
      - name: Setup
        shell: powershell
        run: |
          ./Tools/setup.ps1
          Invoke-Build -Task ShowInfo
      - name: Test
        shell: powershell
        run: |
          Invoke-Build -Task Test
