on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_module:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          ./Tools/setup.ps1
          Invoke-Build -Task ShowInfo
      - name: Build
        run: |
          Invoke-Build -Task Clean, Build
