name: Create Release and Publish

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Validate release tag
        id: release_ref
        uses: AtlassianPS/AtlassianPS.Standards/.github/actions/resolve-release-tag@bd26873fac8ed93eb3b29ea2be20a956394479cb # v0.1.10+

      - name: Download artifact from commit that got tagged
        uses: dawidd6/action-download-artifact@v21
        with:
          workflow: ci.yml
          workflow_conclusion: success
          commit: ${{ steps.release_ref.outputs.release_sha }}
          name: Release
          path: ./Release/
          if_no_artifact_found: fail

      - uses: AtlassianPS/AtlassianPS.Standards/.github/actions/setup-powershell@198212f8a114e8382801678dc59295793a5de288 # v0.1.10

      - name: Publish module
        run: |
          Invoke-Build -Task Publish `
            -VersionToPublish ${{ steps.release_ref.outputs.release_tag }} `
            -PSGalleryAPIKey ${{ secrets.PSGALLERY_API_KEY }}
        shell: pwsh

      - name: Build release notes from changelog
        id: changelog
        uses: MatteoCampinoti94/changelog-to-release@v1.0.6
        with:
          version-name: ${{ steps.release_ref.outputs.release_version }}
          configuration: ./.github/changelog.configuration.json

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v3
        with:
          body: ${{ steps.changelog.outputs.body }}
          files: ./Release/JiraPS.zip
          fail_on_unmatched_files: true
          draft: false
          tag_name: ${{ steps.release_ref.outputs.release_tag }}
          name: ${{ steps.release_ref.outputs.release_tag }}
          prerelease: ${{ contains(steps.release_ref.outputs.release_tag, 'alpha') || contains(steps.release_ref.outputs.release_tag,
            'beta') || contains(steps.release_ref.outputs.release_tag, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
